version: '3.3'
services:
    application:
        container_name: dto-handler_bundle_app
        image: richcongress/php:8.0
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
